---
- include: vars.yml

- include: install_server.yml
  when: nfs_server
- include: setup_server.yml
  when: nfs_server

- include: install_client.yml
  when: nfs_client
- include: setup_client.yml
  when: nfs_client


#https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html