---
- name: Mount nfs share
  mount:
    fstype: nfs
    src: "{{ item.src }}"
    path: "{{ item.mount_point }}"
    state: "{{ item.deleted|default(false) | ternary('absent', 'mounted') }}"
  with_items: ["{{ nfs_client_mounts|default([]) }}"]
