---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure mount folder exists
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - /exports/home/
        - /exports/ro/
        - /exports/old_ro/

  vars:
    nfs_server: yes
    nfs_server_shares:
      - path: /exports/home/
      - path: /exports/ro/
        mount_from: /exports/old_ro/
        allow:
          - 127.0.0.1
          - ip: 10.0.1.0/24
          - ip: 10.0.0.1
            options: (rw,sync)
          - ip: 10.0.0.2
            options:
              - rw
              - sync
              - nohide
        options: (ro,sync)

    nfs_client: yes
    nfs_client_mounts:
      - src: 127.0.0.1:/exports/home/
        mount_point: /mnt/nfs_home/
        deleted: false

      - src: 127.0.0.1:/exports/ro/
        mount_point: /mnt/nfs_ro/
        deleted: false


  roles:
    - role: ansible-role-nfs
